image: ruby:2.5

stages:
  - build
  - deploy

cache:
  paths:
    - vendor

before_script:
  - apt-get update -yqqq
  - apt-get install -y nodejs
  - bundle install --path vendor

build:
  stage: build
  script:
    - bundle exec middleman build --verbose

# To see if issues are coming from invalid articles or from somewhere else
build_without_articles:
  stage: build
  script:
    - rm -rf source/blog
    - bundle exec middleman build --verbose

deploy_preprod:
  stage: deploy
  script:
    - bundle exec middleman deploy --verbose
  environment:
    name: preproduction
    url: https://preprod.dev.unixcorn.org/
  only:
    - devel

deploy_prod:
  stage: deploy
  script:
    - bundle exec middleman deploy --verbose
  environment:
    name: production
    url: https://unixcorn.org/
  only:
    - master
